on:
  push:
    branches:
      - master
    paths:
      - 'frontend/dist/**'
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.prod_key }}
        SOURCE: '/frontend/dist/*'
        REMOTE_HOST: '${{ secrets.SSH_SERVER}}'
        REMOTE_USER: '${{ secrets.SSH_USER }}'
        REMOTE_PORT: ${{secrets.SSH_PORT}}
        TARGET: '/eaas.glazedproductions.com/'