on:
  push:
    branches:
      - master
    paths:
      - 'frontend/dist/**'
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        server: '${{ secrets.ftp_server}}'
        username: '${{ secrets.ftp_username }}'
        password: '${{ secrets.ftp_password }}'
        ssh_private_key: ${{ secrets.prod_key }}
        local_path: 'frontend/dist/*'
