on:
  push:
    branches:
      - master
    paths:
      - 'frontend/dist/**'
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: '${{ secrets.SSH_USER }}'
        server: '${{ secrets.SSH_SERVER}}'
        port: ${{secrets.SSH_PORT}}
        ssh_private_key: ${{ secrets.prod_key }}
        local_path: './frontend/dist/*'
        remote_path: 'eaas.glazedproductions.com'